# Generated by Django 4.0.6 on 2023-02-28 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_pydantic_field._migration_serializers
import django_pydantic_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0010_attachment_file_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(default='')),
                ('questions', models.JSONField()),
                ('points', models.IntegerField()),
                ('is_hidden', models.BooleanField(default=True)),
                ('test_mode', models.CharField(choices=[('auto', 'Automated only testing'), ('manual', 'Manual only testing'), ('auto_and_manual', 'Manual then automated testing')], default='auto', max_length=30)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='lesson.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django_pydantic_field.fields.PydanticSchemaField(config=None, default=[], schema=django_pydantic_field._migration_serializers.GenericContainer(list, (str,)))),
                ('score', models.IntegerField()),
                ('status', models.CharField(choices=[('await', 'AWAIT VERIFICATION'), ('verified', 'VERIFIED')], default='AWAIT VERIFICATION', max_length=30)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_solutions', to='exam.examinationform')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_solutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
