# Generated by Django 4.0.6 on 2023-02-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsolution',
            name='answers',
        ),
        migrations.AddField(
            model_name='examsolution',
            name='correct_questions_indexes',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='examsolution',
            name='user_answers',
            field=models.JSONField(default=[]),
        ),
    ]
