# Generated by Django 4.0.6 on 2023-03-03 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0004_alter_examsolution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationform',
            name='students',
            field=models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
