# Generated by Django 4.0.6 on 2023-03-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_examinationform_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsolution',
            name='status',
            field=models.CharField(choices=[('await', 'AWAIT VERIFICATION'), ('verified', 'VERIFIED')], default='await', max_length=30),
        ),
    ]
