# Generated by Django 4.0.6 on 2023-03-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_examinationform_description'),
        ('exam', '0006_remove_examinationform_students'),
    ]

    operations = [
    ]
