# Generated by Django 4.0.6 on 2023-03-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_examsolution_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinationform',
            old_name='points',
            new_name='max_points',
        ),
        migrations.RenameField(
            model_name='examsolution',
            old_name='correct_questions_indexes',
            new_name='question_verdicts',
        ),
        migrations.RenameField(
            model_name='examsolution',
            old_name='score',
            new_name='solution_points',
        ),
    ]
