# Generated by Django 4.0.6 on 2023-03-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_merge_20230305_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinationform',
            old_name='points',
            new_name='max_points',
        ),
        migrations.RenameField(
            model_name='examsolution',
            old_name='correct_questions_indexes',
            new_name='question_verdicts',
        ),
        migrations.RenameField(
            model_name='examsolution',
            old_name='score',
            new_name='solution_points',
        ),
        migrations.AlterField(
            model_name='examsolution',
            name='status',
            field=models.CharField(choices=[('await', 'AWAIT VERIFICATION'), ('verified', 'VERIFIED')], default='await', max_length=30),
        ),
    ]