# Generated by Django 3.1.8 on 2021-05-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20210511_0235'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseassignteacher',
            unique_together={('course', 'user')},
        ),
    ]
