# Generated by Django 3.1.3 on 2021-01-06 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210106_1721'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigns', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
