# Generated by Django 3.1.8 on 2021-12-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210521_1008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseassignteacher',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='courseassignstudent',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='only_one_assignment_student'),
        ),
        migrations.AddConstraint(
            model_name='courseassignteacher',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='only_one_assignment_teacher'),
        ),
    ]
