# Generated by Django 3.1.3 on 2021-01-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20210117_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/'),
        ),
    ]
