# Generated by Django 3.1.3 on 2021-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20210121_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/'),
        ),
    ]
