# Generated by Django 4.0.6 on 2024-01-11 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('users', '0008_alter_resetpasswordtoken_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroupAssignStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.coursegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroupAssignTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.coursegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigns_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseassignteacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseassignteacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseAssignStudent',
        ),
        migrations.DeleteModel(
            name='CourseAssignTeacher',
        ),
        migrations.AddConstraint(
            model_name='coursegroupassignteacher',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='only_one_assignment_teacher'),
        ),
        migrations.AddConstraint(
            model_name='coursegroupassignstudent',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='only_one_assignment_student'),
        ),
    ]
