# Generated by Django 4.0.6 on 2023-12-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('users', '0008_alter_resetpasswordtoken_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseAssignStudent',
            new_name='GroupAssignStudent',
        ),
        migrations.RenameModel(
            old_name='CourseAssignTeacher',
            new_name='GroupAssignTeacher',
        ),
        migrations.RemoveConstraint(
            model_name='groupassignstudent',
            name='only_one_assignment_student',
        ),
        migrations.RemoveConstraint(
            model_name='groupassignteacher',
            name='only_one_assignment_teacher',
        ),
        migrations.RemoveField(
            model_name='groupassignstudent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='groupassignteacher',
            name='course',
        ),
        migrations.AddField(
            model_name='groupassignstudent',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupassignteacher',
            name='group',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='groupassignstudent',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='only_one_assignment_student'),
        ),
        migrations.AddConstraint(
            model_name='groupassignteacher',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='only_one_assignment_teacher'),
        ),
    ]
