# Generated by Django 4.0.6 on 2023-12-15 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_courseassignstudent_groupassignstudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupassignteacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigns_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
