# Generated by Django 5.1.2 on 2025-03-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_coursegroupassignstudent_coursegroupassignteacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='study_group',
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
    ]
