# Generated by Django 4.0.6 on 2023-12-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_group_coursegroup_and_more'),
        ('users', '0010_alter_groupassignteacher_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupAssignStudent',
            new_name='CourseGroupAssignStudent',
        ),
        migrations.RenameModel(
            old_name='GroupAssignTeacher',
            new_name='CourseGroupAssignTeacher',
        ),
    ]
