version: "3.3"

services:

    database:
        container_name: database
        image: postgres:14
        env_file:
            - ".docker/conf/common.env"
        volumes:
            - ".docker/conf/postgres/postgresql.conf:/etc/postgresql/postgresql.conf"
        networks:
            - db-net
        ports:
            - "5432:5432"

    backend:
        container_name: backend
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
        image: backend:latest
        command: "sh /application/.docker/conf/gunicorn/django-dev.sh"
        volumes:
            - "./:/application"
        working_dir: /application
        depends_on:
            - database
            - redis
        env_file:
            - ".docker/conf/common.env"
            - ".docker/conf/server.env"
        environment:
            PYTHONUNBUFFERED: 1
        ports:
            - "8000:8000"
        networks:
            - db-net
            - nginx-net

    redis:
        container_name: redis
        image: redis:5.0.6-alpine
        networks:
            - db-net

    beat:
        container_name: beat
        image: backend:latest
        command: "sh /application/.docker/conf/gunicorn/celery.sh"
        volumes:
            - "./:/application"
        working_dir: /application
        env_file:
            - ".docker/conf/common.env"
            - ".docker/conf/server.env"
        networks:
            - db-net
        ports:
            - "7999:7999"
        depends_on:
            - database
            - redis
            - backend


networks:
    db-net:
    nginx-net:
