# Generated by Django 3.1.8 on 2022-07-21 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cathie', '0002_auto_20220721_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catsaccount',
            name='last_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
