# Generated by Django 3.1.3 on 2021-01-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cathie', '0002_auto_20210117_0854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatsProblem',
        ),
    ]
