# Generated by Django 4.0.6 on 2022-07-30 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cathie', '0003_auto_20220721_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catsaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cats_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
