# Generated by Django 3.1.3 on 2021-01-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cathie', '0003_delete_catsproblem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatsSubmit',
        ),
    ]
