# Generated by Django 4.0.6 on 2022-12-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathie', '0004_alter_catsaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsaccount',
            name='cats_user_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
