# Generated by Django 3.1.3 on 2021-01-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseschedule',
            old_name='course_id',
            new_name='course',
        ),
    ]
