# Generated by Django 3.1.3 on 2021-01-12 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210112_0748'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_auto_20210106_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ManyToManyField(related_name='staff_for', through='users.CourseAssignTeacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='student_for', through='users.CourseAssignStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
