# Generated by Django 3.1.3 on 2021-01-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210112_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cats_id',
            field=models.IntegerField(null=True),
        ),
    ]
