# Generated by Django 3.1.3 on 2021-05-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0005_auto_20210510_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='week_schedule',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
