# Generated by Django 3.1.3 on 2021-05-11 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0006_auto_20210510_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule',
                                    to='course.course'),
        ),
    ]
