# Generated by Django 3.1.3 on 2021-05-11 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0007_auto_20210511_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule',
                                       to='course.course'),
        ),
    ]
