# Generated by Django 3.1.8 on 2021-11-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20210511_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='de_options',
            field=models.CharField(default='', max_length=512),
        ),
    ]
