# Generated by Django 3.1.8 on 2021-11-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_de_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='de_options',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
