# Generated by Django 3.1.8 on 2022-06-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20211111_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cats_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
