# Generated by Django 4.0.6 on 2023-12-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_course_cats_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
