# Generated by Django 5.1.2 on 2025-03-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_course_staff_remove_course_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseLink',
        ),
    ]
