# Generated by Django 4.0.6 on 2024-01-11 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_coursegroupassignstudent_coursegroupassignteacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='staff',
            field=models.ManyToManyField(related_name='staff_for', through='users.CourseGroupAssignTeacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='students',
            field=models.ManyToManyField(related_name='student_for', through='users.CourseGroupAssignStudent', to=settings.AUTH_USER_MODEL),
        ),
    ]
