# Generated by Django 4.0.6 on 2023-12-04 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_rename_courseassignstudent_groupassignstudent_and_more'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='staff',
            field=models.ManyToManyField(related_name='staff_for', through='users.GroupAssignTeacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='student_for', through='users.GroupAssignStudent', to=settings.AUTH_USER_MODEL),
        ),
    ]
