# Generated by Django 4.0.6 on 2023-12-15 11:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0012_remove_course_staff_remove_course_students'),
        ('users', '0010_alter_groupassignteacher_user'),
        ('group', '0003_grouplink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CourseGroup',
        ),
        migrations.RenameModel(
            old_name='GroupLink',
            new_name='CourseGroupLink',
        ),
    ]
