# Generated by Django 3.1.8 on 2021-06-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseprogress',
            old_name='lessons',
            new_name='progress',
        ),
    ]
