# Generated by Django 3.1.8 on 2021-06-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20210615_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='attendance',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='attendance',
            field=models.ManyToManyField(null=True, related_name='course_attendance', to='rating.Attendance'),
        ),
    ]
