# Generated by Django 3.1.8 on 2021-06-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_delete_lessonprogress'),
        ('rating', '0003_auto_20210615_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress', to='lesson.lesson'),
        ),
    ]
