# Generated by Django 3.1.8 on 2021-06-16 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20210615_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='attendance',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.attendance'),
        ),
    ]
