# Generated by Django 3.1.8 on 2021-06-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20210616_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='attendance',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='attendance',
            field=models.ManyToManyField(to='rating.Attendance'),
        ),
    ]
