# Generated by Django 4.0.6 on 2025-02-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0021_alter_submit_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingProblem',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.problem')),
                ('input_output', models.JSONField(default=list)),
                ('time_limit', models.FloatField(default=1.0)),
                ('memory_limit', models.IntegerField(default=128)),
            ],
            options={
                'verbose_name': 'Testing Problem',
                'verbose_name_plural': 'Testing Problems',
            },
            bases=('problem.problem',),
        ),
        migrations.CreateModel(
            name='TestingSubmit',
            fields=[
                ('submit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.submit')),
                ('testing_results', models.JSONField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('memory_used', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Testing Submit',
                'verbose_name_plural': 'Testing Submits',
            },
            bases=('problem.submit',),
        ),
        migrations.CreateModel(
            name='InProgressTesting',
            fields=[
                ('submit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testing.testingsubmit')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'In Progress Testing',
                'verbose_name_plural': 'In Progress Testing',
            },
        ),
        migrations.CreateModel(
            name='TestingQueue',
            fields=[
                ('submit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testing.testingsubmit')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testing Queue',
                'verbose_name_plural': 'Testing Queues',
            },
        ),
    ]
