# Generated by Django 4.0.6 on 2023-02-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_attachment_file_format'),
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='lesson.lesson'),
        ),
    ]
