# Generated by Django 4.0.6 on 2023-02-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_test_question_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='question_list',
            new_name='questions',
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='test_mode',
            field=models.CharField(choices=[('auto', 'Automated only testing'), ('manual', 'Manual only testing'), ('auto_and_manual', 'Manual then automated testing')], default='auto', max_length=30),
        ),
    ]
