# Generated by Django 4.0.6 on 2023-02-27 13:14

from django.db import migrations
import django_pydantic_field._migration_serializers
import django_pydantic_field.fields
import test.models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_testsolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, schema=django_pydantic_field._migration_serializers.GenericContainer(list, (test.models.Question,))),
        ),
    ]
