# Generated by Django 4.0.6 on 2023-02-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_alter_test_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.JSONField(),
        ),
    ]
