# Generated by Django 3.1.3 on 2021-04-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20210319_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonProgress',
        ),
    ]
