# Generated by Django 3.1.3 on 2021-01-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20210106_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
