# Generated by Django 3.1.3 on 2021-01-10 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0003_lesson_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('text', 'Text'), ('url', 'Url')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='lesson.lesson'),
        ),
    ]
