# Generated by Django 3.1.8 on 2022-06-17 09:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_delete_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='content',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='private media'), upload_to=''),
        ),
    ]
