# Generated by Django 4.0.6 on 2022-11-19 14:58

from django.db import migrations, models
import django.db.models.deletion
import lesson.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_lessoncontent_is_teacher_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_url', models.FileField(upload_to=lesson.models.attachment_file_name)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='lesson.lessoncontent')),
            ],
        ),
    ]
