# Generated by Django 3.1.3 on 2021-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='solved',
            field=models.JSONField(null=True),
        ),
    ]
