# Generated by Django 4.0.6 on 2022-11-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_url', models.CharField(max_length=500)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment', to='lesson.lessoncontent')),
            ],
        ),
        migrations.DeleteModel(
            name='Attachments',
        ),
    ]
