# Generated by Django 3.1.3 on 2021-03-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lesson', '0006_auto_20210203_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
