# Generated by Django 4.0.6 on 2022-11-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_attachment_delete_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='material',
        ),
        migrations.AddField(
            model_name='attachment',
            name='material_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='lesson.lessoncontent'),
        ),
    ]
