# Generated by Django 4.0.6 on 2022-11-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_remove_attachment_material_attachment_material_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='material_id',
            new_name='material',
        ),
    ]
