# Generated by Django 4.0.6 on 2022-11-20 11:54

from django.db import migrations, models
import lesson.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_rename_material_id_attachment_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_url',
            field=models.FileField(upload_to=lesson.models.attachment_file_name),
        ),
    ]
