# Generated by Django 4.0.6 on 2022-11-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_alter_attachment_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_format',
            field=models.CharField(default='', max_length=50),
        ),
    ]
