# Generated by Django 4.0.6 on 2023-03-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_alter_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_format',
            field=models.CharField(default='', max_length=100),
        ),
    ]
