
# Generated by Django 4.0.6 on 2023-03-15 09:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_alter_attachment_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='content',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='private media'), upload_to=''),
        ),
    ]
