# Generated by Django 5.1.2 on 2025-02-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0015_alter_lessoncontent_is_teacher_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='deadline',
        ),
    ]
