# Generated by Django 3.1.3 on 2021-03-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatsSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('id_to_check', models.IntegerField(default=None, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sending_result', models.JSONField(null=True)),
                ('testing_result', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('manual', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('CW', 'classwork'), ('HW', 'homework'), ('EX', 'extratasks')], default='CW', max_length=2)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('cats_id', models.IntegerField(null=True)),
                ('cats_material_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('WA', 'Wrong answer'), ('OK', 'OK'), ('NP', 'NP'), ('AW', 'Awaiting manual verification'), ('RJ', 'Rejected'), ('CE', 'Compilation error'), ('LI', 'Linter error'), ('RE', 'Run-time error'), ('PE', 'Presentation error'), ('TL', 'Time limit exceeded'), ('IL', 'Idleness limit exceeded'), ('ML', 'Memory limit exceeded'), ('WL', 'Write limit exceeded'), ('SV', 'Security violation'), ('IS', 'Ignored submit'), ('MR', 'Rejected by manual verification'), ('BA', 'Banned')], default='NP', max_length=2)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submits', to='problem.problem')),
            ],
        ),
    ]
