# Generated by Django 3.1.3 on 2021-01-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20210106_1721'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='lesson.lesson'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='status',
            field=models.CharField(choices=[('WA', 'Wrong answer'), ('OK', 'OK'), ('NP', 'NP')], max_length=2),
        ),
    ]
