# Generated by Django 3.1.3 on 2021-03-19 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
        ('lesson', '0002_auto_20210319_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='lesson.lesson'),
        ),
        migrations.AddField(
            model_name='problem',
            name='students',
            field=models.ManyToManyField(related_name='problems_with_submits', through='problem.Submit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catssubmit',
            name='submit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cats_submit', to='problem.submit'),
        ),
    ]
