# Generated by Django 3.1.3 on 2021-01-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20210106_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='manual',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('CW', 'classwork'), ('HW', 'homework')], max_length=2, null=True),
        ),
    ]
