# Generated by Django 3.1.3 on 2021-01-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20210111_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='completed',
        ),
        migrations.AddField(
            model_name='problem',
            name='cats_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
