# Generated by Django 3.1.3 on 2021-04-25 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0003_submit_submit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='submit_date',
        ),
        migrations.AddField(
            model_name='submit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
