# Generated by Django 3.1.3 on 2021-01-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0004_auto_20210117_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('CW', 'classwork'), ('HW', 'homework')], default=('CW', 'classwork'),
                                   max_length=2),
        ),
    ]
