# Generated by Django 3.1.3 on 2021-04-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20210425_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submit',
            options={'ordering': ['id']},
        ),
    ]
