# Generated by Django 3.1.3 on 2021-05-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20210427_0037'),
        ('problem', '0005_auto_20210510_1802'),
    ]

    operations = [
    ]
