# Generated by Django 3.1.8 on 2021-11-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_problemstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='de_options',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
