# Generated by Django 3.1.8 on 2021-11-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_problem_de_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='de_id',
            field=models.CharField(default=502, max_length=5),
            preserve_default=False,
        ),
    ]
