# Generated by Django 3.1.3 on 2021-01-30 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0008_auto_20210130_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='students',
            field=models.ManyToManyField(related_name='_problem_students_+', through='problem.Submit',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='authored_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
