# Generated by Django 3.1.3 on 2021-01-30 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0009_auto_20210130_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='students',
            field=models.ManyToManyField(related_name='problems_with_submits', through='problem.Submit',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submits',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
