# Generated by Django 3.1.8 on 2021-11-24 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0009_submit_de_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('message', 'Message to display'), ('cats_answer', 'Check answer from cats'), ('status_change', 'Submit status changed to'), ('submit', 'Submit created')], max_length=16)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_events', to='problem.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
