# Generated by Django 3.1.8 on 2021-12-02 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0010_logevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='logevent',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_log_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logevent',
            name='submit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_events', to='problem.submit'),
        ),
        migrations.AddField(
            model_name='submit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_submits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logevent',
            name='type',
            field=models.CharField(choices=[('submit', 'Submit created'), ('message', 'Message to display'), ('status_change', 'Submit status changed to'), ('cats_answer', 'Check answer from cats'), ('cats_submit', 'Cats submit created')], max_length=16),
        ),
    ]
