# Generated by Django 3.1.3 on 2021-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_auto_20210130_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='status',
            field=models.CharField(choices=[('WA', 'Wrong answer'), ('OK', 'OK'), ('NP', 'NP'), ('AW', 'Awaiting manual verification'), ('RJ', 'Rejected'), ('CE', 'Compilation error'), ('LI', 'Linter error'), ('RE', 'Run-time error'), ('PE', 'Presentation error'), ('TL', 'Time limit exceeded'), ('IL', 'Idleness limit exceeded'), ('ML', 'Memory limit exceeded'), ('WL', 'Write limit exceeded'), ('SV', 'Security violation'), ('IS', 'Ignored submit'), ('MR', 'Rejected by manual verification'), ('BA', 'Banned')], default='NP', max_length=2),
        ),
    ]
