# Generated by Django 3.1.8 on 2021-12-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_auto_20211202_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='catssubmit',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logevent',
            name='type',
            field=models.CharField(choices=[('submit', 'Submit created'), ('message', 'Message to display'), ('status_change', 'Submit status changed to'), ('cats_answer', 'Check answer from cats'), ('cats_submit', 'Cats submit created'), ('cats_error', 'Cats error type')], max_length=16),
        ),
    ]
