# Generated by Django 3.1.3 on 2021-02-07 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0011_auto_20210203_1553'),
        ('problem', '0011_auto_20210205_0001'),
    ]

    operations = [
    ]
