# Generated by Django 3.1.8 on 2022-01-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_auto_20211230_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logevent',
            options={'ordering': ('created_at', 'id')},
        ),
    ]
