# Generated by Django 3.1.3 on 2021-03-09 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0012_merge_20210207_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='cats_request_id',
        ),
        migrations.CreateModel(
            name='CatsSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('is_sent', models.BooleanField(default=False)),
                ('response', models.JSONField(null=True)),
                ('submit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                             related_name='cats_submit', to='problem.submit')),
            ],
        ),
    ]
