# Generated by Django 3.1.8 on 2022-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_auto_20220111_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_mod',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
