# Generated by Django 3.1.8 on 2022-06-17 01:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_auto_20220111_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='content',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='private media'), upload_to=''),
        ),
    ]
