# Generated by Django 3.1.3 on 2021-03-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0013_auto_20210309_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catssubmit',
            old_name='response',
            new_name='sending_result',
        ),
        migrations.AddField(
            model_name='catssubmit',
            name='id_to_check',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='catssubmit',
            name='testing_result',
            field=models.JSONField(null=True),
        ),
    ]
