# Generated by Django 4.0.6 on 2022-07-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_alter_logevent_options_alter_catssubmit_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='de_id',
            field=models.CharField(max_length=12),
        ),
    ]
