# Generated by Django 4.0.6 on 2022-08-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_alter_submit_de_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catssubmit',
            name='id_to_check',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='catssubmit',
            name='sending_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catssubmit',
            name='testing_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
