# Generated by Django 4.0.6 on 2022-08-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_alter_catssubmit_id_to_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_mode',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
