# Generated by Django 4.0.6 on 2022-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0017_problem_test_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logevent',
            name='type',
            field=models.CharField(choices=[('submit', 'Submit created'), ('message', 'Message to display'), ('status_change', 'Submit status changed to'), ('cats_answer', 'Check answer from cats'), ('cats_submit', 'Cats submit created'), ('cats_error', 'Cats error type'), ('awaiting_manual', 'Awaiting manual verification')], max_length=16),
        ),
    ]
