# Generated by Django 3.2.15 on 2022-10-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0018_alter_logevent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_mode',
            field=models.CharField(choices=[('auto', 'Automated only problem testing'), ('manual', 'Manual only problem testing'), ('auto_and_manual', 'Manual then automated problem testing')], default='auto', max_length=30),
        ),
    ]
