# Generated by Django 4.0.6 on 2023-03-18 04:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0019_alter_problem_test_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='content',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='private media'), upload_to=''),
        ),
    ]
