# Generated by Django 4.0.6 on 2023-04-23 12:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0020_alter_submit_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='content',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='private_media'), upload_to=''),
        ),
    ]
